name: yene_farm
description: Ethiopian Farmer Marketplace with AI Assistant

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.7
  intl: ^0.20.2
  share_plus: ^7.0.1
  url_launcher: ^6.1.9
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  speech_to_text: ^7.3.0
  flutter_tts: ^3.8.3
  camera: ^0.10.5
  image: ^4.0.17
  path_provider: ^2.0.15
  path: ^1.8.3
  supabase_flutter: ^2.10.3
  supabase: ^2.10.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
  # fonts: (commented out until font files are added)
  # - family: Inter
  #   fonts:
  #     - asset: assets/fonts/Inter-Regular.ttf
  #     - asset: assets/fonts/Inter-Medium.ttf
  #       weight: 500
  #     - asset: assets/fonts/Inter-SemiBold.ttf
  #       weight: 600
  #     - asset: assets/fonts/Inter-Bold.ttf
  #       weight: 700

dependency_overrides:
  # Force newer webview platform implementation which includes Android `namespace` in build files.
  webview_flutter_android: ^4.10.5
  webview_flutter: ^4.13.0