name: CI Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t yene-backend:latest .
      - name: Run container
        run: docker run -d --name yene-backend -p 8080:8080 -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} -e SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} yene-backend:latest
      - name: Wait for health
        run: |
          for i in {1..20}; do
            if curl -sSf http://localhost:8080/health; then exit 0; fi
            sleep 1
          done
          exit 1
      - name: Run smoke script
        run: node scripts/smoke.js
